### ISSUE TITLE
Burps browser doesnt work in this version

### ISSUE THREAD

**Issue by RobiSE9722** [cyb3rzest/Burp-Suite-Pro#1]
I have tried both Kali and ParrotOS.
In both systems burps browser wont start.
First i get a error that sandboxing is not supported on the OS, when i turn this off in burps settings to allow the broser to run without sandoxing the browser starts but glitches out. In Kali i get a massive graphical glitch and in parrot the browser icon is visible in the taskbar but the browser window itself is invisible. This is odd considering older cracks and the community edition work fine on both systems.

**Comment by cyb3rzest** [comment]
Can you provide the screenshot?
