### ISSUE TITLE
if you do not want to be hacked,dont install it in your system

### ISSUE THREAD

**Issue by Ammitte** [cyb3rzest/Burp-Suite-Pro#11]

**Comment by BigGod12** [comment]
i did already, how can i know if i`m been hacked already, though the code in "Linux_setup.sh" seems to be straitfoward and downloading the burp pro from portswigger directly, but i do not know about the loader.jar

**Comment by legiorange** [comment]
I decompiled loader.jar and nothing suspicious.

**Comment by cyb3rzest** [comment]
I know @legiorange that’s why i shared it here. If it contains anything suspicious, I won’t share it here. There are bunch of malicious content available on here that can use for comprising someone system, but I don’t like those

**Comment by legiorange** [comment]
> I know @legiorange that’s why i shared it here. If it contains anything suspicious, I won’t share it here. There are bunch of malicious content available on here that can use for comprising someone system, but I don’t like those

However, using this script, I can't login to Kali Linux.

The password has changed.I haven't analyzed that yet.
