### ISSUE TITLE
Terminal  error 

### ISSUE THREAD

**Issue by ho1x1ow** [cyb3rzest/Burp-Suite-Pro#15]
After installation my terminal isn't showing root access and giving back the error dircolours not found and any command in root mode is not running. Also after that when I reboot the system I got stuck at login loop error then i uninstalled my system and reinstalled it I need pro version for testing can you please help me with it .

**Comment by ricardev2023** [comment]
There is an error in the bash script:

`echo "export PATH=\$PATH:\$JAVA_HOME/bin" | sudo tee -a /etc/environment` it is taking \$PATH and \$JAVA_HOME as strings and not as pointers or references.

You should change this line with:

`echo "export PATH=$PATH:$JAVA_HOME/bin" | sudo tee -a /etc/environment`

Before running the script for the first time on your system. Then it will work properly.

If you already run the script, you should check the PATH env variable of your standard user and then copy it in this command as root:

`echo "export PATH=PATH_ON_YOUR_STANDARD_USER:$JAVA_HOME/bin" | sudo tee -a /etc/environment`

And it should solve all your problems.

**Comment by cyb3rzest** [comment]
@ricardev2023 I have updated this issue and also shared your name in the script as well
