### ISSUE TITLE
IT Killed my kali nothing works 

### ISSUE THREAD

**Issue by Jonathan9889** [cyb3rzest/Burp-Suite-Pro#16]
it cant find any of my commands not bash, not mv, cp .
tried to run the echo "export PATH=PATH_ON_YOUR_STANDARD_USER:$JAVA_HOME/bin" | sudo tee -a /etc/environment

nothing works

**Comment by cyb3rzest** [comment]
Are you on root user or on normal user?

**Comment by Jonathan9889** [comment]
root it cant be normal user

**Comment by ricardev2023** [comment]
Did you find out a solution??
