### ISSUE TITLE
Burpssuit domand a license key

### ISSUE THREAD

**Issue by finanya99** [cyb3rzest/Burp-Suite-Pro#17]
after all instalation on my kali linux a notification pop up and tell me to add a liscense key

**Comment by cyb3rzest** [comment]
Cut that, and run burploader first and then check auto run and ignore update. Then run burpsuite

**Comment by ricardev2023** [comment]
@finanya99 Did you find out a solution?

**Comment by cyb3rzest** [comment]
Run the command with 
sudo burpsuite
