### ISSUE TITLE
Error: java.lang.ClassNotFoundException: burp.StartBurp (VER: 2023.3.5)

### ISSUE THREAD

**Issue by Invernomut0** [cyb3rzest/Burp-Suite-Pro#2]
Hi,
I get this error on version 2023.3.5:

java "--illegal-access=permit" "-javaagent:/Users/lorenzov/Burp-Loader/loader.jar" "-noverify" "-jar" "/Users/lorenzov/Burp-Loader/burpsuite_pro_v.jar"
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
    ____                      __                    __             __ __
   / __ )__  ___________     / /   ____  ____ _____/ /__  _____   / //_/__  __  ______ ____  ____
  / __  / / / / ___/ __ \   / /   / __ \/ __ `/ __  / _ \/ ___/  / ,< / _ \/ / / / __ `/ _ \/ __ \
 / /_/ / /_/ / /  / /_/ /  / /___/ /_/ / /_/ / /_/ /  __/ /     / /| /  __/ /_/ / /_/ /  __/ / / /
/_____/\__,_/_/  / .___/  /_____/\____/\__,_/\__,_/\___/_/     /_/ |_\___/\__, /\__, /\___/_/ /_/
                /_/                                                      /____//____/
Github:https://github.com/h3110w0r1d-y/BurpLoaderKeygen 商业使用请购买正版软件！
Errore: impossibile trovare o caricare la classe principale burp.StartBurp
Causato da: java.lang.ClassNotFoundException: burp.StartBurp

**Comment by cyb3rzest** [comment]
Have you checked the box "Auto Run"?

**Comment by wraithhitek** [comment]
Same issue with me

**Comment by wraithhitek** [comment]
![16838204109332878323371818937756](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/79362655/fae91d2b-f850-4457-9e39-17fcab83af4b)

Facing this issue.

**Comment by cyb3rzest** [comment]
Check the “Auto Run” and “ignore updates”

it will start

**Comment by GitGangsta** [comment]
how?

**Comment by cyb3rzest** [comment]
when the burploader opens, it have the check box.
