### ISSUE TITLE
Update to newest verison

### ISSUE THREAD

**Issue by EdwardDK** [cyb3rzest/Burp-Suite-Pro#21]
The newest BS version is like 2023.22 Can we get an update from the one that this tool currently downloads us 2022.22?

Its pretty outdated and it would be nicer if the tool got updated every new major update or year.

Thanks!

**Comment by EdwardDK** [comment]
Also, there are errors downloading JDK 19 and it can't create Java VM

![image](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/73299061/0f0f8ebe-7a7b-4882-8d83-069b3c24144b)

![image](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/73299061/04c1954c-edfc-4d00-a3bb-d3a4c8cc4adf)

![image](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/73299061/71005109-180c-47d8-8235-359e61bdec34)

![image](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/73299061/7dba4991-52da-4257-8b5f-159db313e3fb)

**Comment by cyb3rzest** [comment]
I have tested it in the latest version 2023.12.#

And, its working as charm.

**Comment by EdwardDK** [comment]
Thankyou I will test it out
