### ISSUE TITLE
License activation

### ISSUE THREAD

**Issue by cyclelogic** [cyb3rzest/Burp-Suite-Pro#24]
I ran the setup script as root using sudo. This is the output:
![2024-02-27 06_57_16-kali  Running  - Oracle VM VirtualBox](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/58864066/bf4de0c0-1fab-4878-8d0a-afaea871abe3)

Burpsuite does not stay open and the loader/keygen shows:
![2024-02-27 06_58_00-kali  Running  - Oracle VM VirtualBox](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/58864066/accfbce2-cbd1-4867-af82-074f1a4465c8)

What do I do with the license text and license? If I set Auto Run and Ignore Update and click run nothing happens.

**Comment by karthikedassery** [comment]
I am having the same issue

**Comment by prasgop** [comment]
> I ran the setup script as root using sudo. This is the output: ![2024-02-27 06_57_16-kali Running - Oracle VM VirtualBox](https://private-user-images.githubusercontent.com/58864066/308196522-bf4de0c0-1fab-4878-8d0a-afaea871abe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDUwMDksIm5iZiI6MTcxMDQ0NDcwOSwicGF0aCI6Ii81ODg2NDA2Ni8zMDgxOTY1MjItYmY0ZGUwYzAtMWZhYi00ODc4LThkMGEtYWZhZWE4NzFhYmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE5MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMWYyMDEwZGU1YWY2ZDMwMDAwZTgzN2Q1YmFlZTM5OWY5NzVmNGY4MDIxMGViOGU0Y2IwYTE1NDEyMDg0MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R3hAHrfF8eQEiVVvrIxtFyjrsoI5G-NYdECBoW6CWmM)
> 
> Burpsuite does not stay open and the loader/keygen shows: ![2024-02-27 06_58_00-kali Running - Oracle VM VirtualBox](https://private-user-images.githubusercontent.com/58864066/308196820-accfbce2-cbd1-4867-af82-074f1a4465c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDUwMDksIm5iZiI6MTcxMDQ0NDcwOSwicGF0aCI6Ii81ODg2NDA2Ni8zMDgxOTY4MjAtYWNjZmJjZTItY2JkMS00ODY3LWFmODItMDc0ZjFhNDQ2NWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE5MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0Nzg1ZTA5MzAwOWQ5Mjk0ZWYyMjU5ODVlMWE2OWU2OGU1ZGI0MTY4YzI0NGNhOGY3YjI4ODk4ZDc3ZjcxYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4crOcqWJvJFxFXyZDJgVmzLCx8_SP_fA7v31PyKsszk)
> 
> What do I do with the license text and license? If I set Auto Run and Ignore Update and click run nothing happens.

did you try clicking on that Run?

**Comment by cyclelogic** [comment]
Yes. It leaves the activation box open. How do I provide the correct
activation request?

**Comment by cyclelogic** [comment]
Burp suite pro does not stay open to paste the license key into.

**Comment by cyclelogic** [comment]
I was able to fix the issue by upgrading my JRE. I only needed to change
the "license to xxxx" and it all worked.

Thanks.
