### ISSUE TITLE
Keeps asking for license Registration - Linux

### ISSUE THREAD

**Issue by SnarkyWolfe** [cyb3rzest/Burp-Suite-Pro#26]
When running burpsuite in terminal, it launches and then asks for a license key each and every time. How do we by pass this?
![Screenshot 2024-03-17 095744](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/33639460/8a727aa4-2da4-4b60-8edd-22e761ef4108)

Even if I cd to the directory I downloaded and ran everything, it still does this.

**Comment by mytricker0** [comment]
you have to run with `sudo`
I made a fork where you have the application `Burp Suite Pro Cracked` in you application menu:
like this:
![image](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/58003204/69b2c589-81c3-4690-9403-f62ab91d3af7)


https://github.com/mytricker0/Burp-Suite-Pro

you just have to launch the ./Linux_setup.sh again to install it

**Comment by SnarkyWolfe** [comment]
Lol, cannot believe I forgot to launch with sudo. Thanks for pointing out the fork as well!
