### ISSUE TITLE
JRE 8 isn't supported anymore on the current burp suite version

### ISSUE THREAD

**Issue by DEMON1A** [cyb3rzest/Burp-Suite-Pro#3]
I used your script, the PS1 file for windows installation and it just seems like you're installing Java 8 JRE which causes a JNI error on my machine for some reason, I searched and it seems like this error is related to an un-supported Java version which burp suite doesn't support anymore, Maybe you should update the script to install Java 9 JRE or higher? That's the min requirement for burp suite right now

**Comment by cyb3rzest** [comment]
Jre 8 is working also.
Just check over “auto run”
Still if not its start, provide the screenshot.

and for JRE9, I will check for that and update the script

**Comment by DEMON1A** [comment]
For some reason reinstalling JRE8 ended up fixing the issue for burp-suite, That's actually ODD, Thanks anyways for your response it seems to be okay with JRE8
![image](https://github.com/cyb3rzest/Burp-Suite-Pro/assets/54229853/669e7e04-d56a-4083-90bb-72be9d91abd6)
