### ISSUE TITLE
Trash script by a script kiddie

### ISSUE THREAD

**Issue by basedygt** [cyb3rzest/Burp-Suite-Pro#30]
Trash script downloads and installs unnecessary files and fills up your storage. Learn how to write a script skiddie , `loader.jar` is copy pasted and you can't even write a simple installer i would die if i were that bad.

**Comment by gisforgirard** [comment]
i bet you're a l33t h4x0r and have a ton of friends

**Comment by basedygt** [comment]
> i bet you're a l33t h4x0r and have a ton of friends
truth hits harder you indians are shi* always copy paste other stuffs and claim to be professional . Regarding my skills i have reported valid bugs on hackerone and even received bounty . what have you done copy paste a script of a skiddie lmao

**Comment by basedygt** [comment]
> i bet you're a l33t h4x0r and have a ton of friends

yh lol i probably have found and reported more bugs than your age kiddie

**Comment by linuxisawezum** [comment]
i use arch btw

**Comment by StellarSt0rm** [comment]
> i use arch btw

I use NixOS btw

**Comment by cyb3rzest** [comment]
@basedygt thankyou for your opinion..
I will put your opinion in the trash-bin🗑️ as per your own brain capabilities ☺️

**Comment by basedygt** [comment]
> @basedygt thankyou for your opinion.. I will put your opinion in the trash-bin🗑️ as per your own brain capabilities ☺️

That was an insult not an opinion kid. Typical skiddie behaviour.

**Comment by cyb3rzest** [comment]
@basedygt yeah, for you it must be an insult, because you yourself is an insult as well as mistake for your parents.☺️

**Comment by basedygt** [comment]
> @basedygt yeah, for you it must be an insult, because you yourself is an insult as well as mistake for your parents.☺️

Mom jokes have been used a lost just like yo mom.
