### ISSUE TITLE
after installing sudo su not working

### ISSUE THREAD

**Issue by piro-piyush** [cyb3rzest/Burp-Suite-Pro#5]
<img width="368" alt="Capture" src="https://github.com/cyb3rzest/Burp-Suite-Pro/assets/141152683/8cc4ee84-bc2d-4892-8986-72c720392246">

**Comment by cyb3rzest** [comment]
You are already in root, and I always use only root user and never faced any issue like this.

Can you elaborate?

**Comment by piro-piyush** [comment]
why its shows command not found instead of u r alreadt root

**Comment by cyb3rzest** [comment]
if you see there, t

**Comment by cyb3rzest** [comment]
if you see there, there is `root@kali` which means you are using as root user. And again there is `command not found: mv` and `command not found: dircolor` which tells there is issue in your `.zshrc` file.

For fixing this issue, simply copy the `.zshrc` file of your normal user to `/root/.zshrc` file

**Comment by izzais** [comment]
remove line added by script in `/etc/environment` fix this.

**Comment by Sanu1999** [comment]
> remove line added by script in `/etc/environment` fix this.

how to do

**Comment by izzais** [comment]
> > remove line added by script in `/etc/environment` fix this.
> 
> how to do.. please elaborate

`sudo su`
`export PATH="/usr/sbin:/usr/bin:/sbin:/bin"`
`nano /etc/environment` or `vim /etc/environment`
delete last 2 line which is 
`export JAVA_HOME=/usr/local/java/jdk19` and `export PATH=\$PATH:\$JAVA_HOME/bin`
