### ISSUE TITLE
After install it cause Login loop in Lightdm and I should switch to GDm3 to fix it

### ISSUE THREAD

**Issue by hoainam125** [cyb3rzest/Burp-Suite-Pro#6]

**Comment by cyb3rzest** [comment]
Haven't used lightdm, but there is issue in source code of lightdm which cause the said issue.
Not only using burp, but also any tool which uses high resource will cause the same issue.

**Comment by ariel8300** [comment]
Hello,
I have a temporary solution.
If you have the login loop, simply press CTRL + F2, then login with your user, then type startx to load the UI back.
