### ISSUE TITLE
unable to use with verson 2023-10-2

### ISSUE THREAD

**Issue by BigGod12** [cyb3rzest/Burp-Suite-Pro#7]
i`m unable to use it with new version of burp pro, though version 2023-10-2 was downloaded, after running the keygen and activating the license key, i keep getting version 2023.2.3 as activated burp, took me almost 8 hours try to fix this, matter of fact i had to install new kali before i realized it from the script and not my other machine
and i need this to work with turbo intruder, the comminuty version is not saving my installed extensions

**Comment by cyb3rzest** [comment]
If you are getting the older version, as due to Kali Linux not being updated, then you can manually download the latest version and then in /usr/share/burpsuite/burpsuite file change the version number and then copy the file to /usr/bin/

Your burpsuite pro latest version will work

**Comment by mmathieu90** [comment]
After validating the license, I downloaded the new version and replaceed the jar file. Then edited burp.bat with the new name "burpsuite_pro_v2023.10.2.jar"

Works for me

**Comment by BigGod12** [comment]
> If you are getting the older version, as due to Kali Linux not being updated, then you can manually download the latest version and then in /usr/share/burpsuite/burpsuite file change the version number and then copy the file to /usr/bin/
> 
> Your burpsuite pro latest version will work



> After validating the license, I downloaded the new version and replaceed the jar file. Then edited burp.bat with the new name "burpsuite_pro_v2023.10.2.jar"
> 
> Works for me

but the new "burpsuite_pro_v2023.10.2.jar" downloaded together when installing the it in the first place, do i need to download it again?? and please how can i located the burp.bat in kali?? burp.bat seems to be for windows, thank you

**Comment by cyb3rzest** [comment]
> > If you are getting the older version, as due to Kali Linux not being updated, then you can manually download the latest version and then in /usr/share/burpsuite/burpsuite file change the version number and then copy the file to /usr/bin/
> > Your burpsuite pro latest version will work
> 
> > After validating the license, I downloaded the new version and replaceed the jar file. Then edited burp.bat with the new name "burpsuite_pro_v2023.10.2.jar"
> > Works for me
> 
> but the new "burpsuite_pro_v2023.10.2.jar" downloaded together when installing the it in the first place, do i need to download it again?? and please how can i located the burp.bat in kali?? burp.bat seems to be for windows, thank you

in linux, in the folder `/usr/share/burpsuite/` you'll find the file named `burpsuite` 
Change the version name in this file then copy that file to `/usr/bin/`

**Comment by BigGod12** [comment]
> If you are getting the older version, as due to Kali Linux not being updated, then you can manually download the latest version and then in /usr/share/burpsuite/burpsuite file change the version number and then copy the file to /usr/bin/
> 
> Your burpsuite pro latest version will work

sorry for late reply, does it means i will recompile "burpsuite" because the main burpsuite.jar has been removed after it successfully downloaded according to the source code of

> If you are getting the older version, as due to Kali Linux not being updated, then you can manually download the latest version and then in /usr/share/burpsuite/burpsuite file change the version number and then copy the file to /usr/bin/
> 
> Your burpsuite pro latest version will work

sorry for late reply, how do i need change the version number for the file "burpsuite" it executable, i`m going to decompile it?? thank you
