### ISSUE TITLE
getting this error in loader command 

### ISSUE THREAD

**Issue by Yaswanth-Mitta** [cyb3rzest/Burp-Suite-Pro#8]
"/usr/lib/jvm/java-11-openjdk-amd64/bin/java" "-javaagent:/usr/share/burpsuite/loader.jar" "-noverify" "-jar" "/usr/share/burpsuite/burpsuite_pro_v2023-10-2.jar"

**Comment by cyb3rzest** [comment]
What error you're getting. Attach screenshot
